# Configuration for Reformata-CMS-Core Deployment

name: "Arbor Heights Bible Church"

server:
  host: 127.0.0.1
  port: 8000
  # timeout:
  #   server: 30
  #   read: 15
  #   write: 15

youtubeapiurl: "https://www.googleapis.com/youtube/v3/search"
url: "https://www.googleapis.com/youtube/v3/search"
youtubechannelid: UCKU147XoMX2tdXt2dmUDX0g